name: CI

on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Set up dependencies
      run: |
        bash .github/workflows/setup-deps.sh
    - name: Set up android dependencies
      run: |
        wget --quiet https://github.com/izgzhen/android-platforms/releases/download/v0.1/android-tools-linux.zip
        unzip -q android-tools-linux.zip -d android-tools-linux
        yes | android-tools-linux/tools/bin/sdkmanager --licenses
        android-tools-linux/tools/bin/sdkmanager 'platforms;android-29'
    # Runs a single command using the runners shell
    - name: Test analyzer
      run: |
        ANDROID_SDK=$PWD/android-tools-linux sbt clean coverage test coverageReport
        ANDROID_SDK=$PWD/android-tools-linux make test-all
    - name: Codecov
      uses: codecov/codecov-action@v1.0.12